name: CD - Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_NAME }} --overwrite-existing

      - name: Create production namespace
        run: kubectl create namespace production || echo "namespace already exists"

      - name: Deploy services to production
        run: kubectl apply -f k8s/ -n production

      - name: Show production services
        run: kubectl get svc -n production
